const test=require('node:test'),assert=require('node:assert/strict'),vm=require('vm'),fs=require('fs'),path=require('path');
const src=fs.readFileSync(path.join(__dirname,'../public/app.js'),'utf8');
function harness(){const els=new Map(),storage=new Map(),timers=new Map();let sequence=0;
 const el=k=>{if(!els.has(k))els.set(k,{value:'',dataset:{},style:{},events:{},disabled:false,classList:{contains:()=>false,add(){},remove(){},toggle(){}},addEventListener(name,fn){this.events[name]=fn},closest:()=>null,setAttribute(){},getAttribute:()=>null});return els.get(k)};
 const area=el('#agreementReason'),budget=el('budget');budget.dataset={budget:'renewable',delta:'-10'};
 const c=vm.createContext({console,AbortSignal,Date,document:{querySelector:el,querySelectorAll:s=>s==='textarea'?[area]:s==='[data-budget]'?[budget]:[]},setTimeout:fn=>{timers.set(++sequence,fn);return sequence},clearTimeout:n=>timers.delete(n),setInterval:()=>0,clearInterval(){},fetch:async()=>({ok:true,json:async()=>({})}),alert(){},confirm:()=>true,window:{scrollTo(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}});
 vm.runInContext(src.slice(0,src.indexOf("\n$('#startBtn').addEventListener")),c);
 vm.runInContext("session={sessionId:'sample',country:'hanbit',status:'in_progress'};step=renderedStep=1;state={agreement:'B',agreementReason:'기존 문장',budget:{renewable:20,disaster:20,tech:20,forest:20,transition:20}}; render=()=>{document.querySelector('#agreementReason').value=state.agreementReason;};bindStep();",c);
 el('input[name="agreement"]:checked').value='B';area.value='기존 문장';return {c,el,area,budget,storage};}
test('typing then budget click preserves latest answer and local draft',async()=>{const h=harness();h.area.value='바로 입력한 새 답안';h.area.events.input();h.budget.events.click();assert.equal(h.area.value,'바로 입력한 새 답안');assert.equal(JSON.parse(h.storage.get('climateDraft:sample')).data.agreementReason,'바로 입력한 새 답안');await vm.runInContext('save(false)',h.c);assert.equal(h.storage.size,0)});
test('changing step before render does not overwrite unseen answers',()=>{const h=harness();vm.runInContext("state.compromise='보존할 절충안';step=2;collect()",h.c);assert.equal(vm.runInContext('state.compromise',h.c),'보존할 절충안')});
test('in-flight save cannot clear a newer unsaved local draft',async()=>{const h=harness();vm.runInContext('let release;fetch=()=>new Promise(r=>release=r)',h.c);const saving=vm.runInContext('save(false)',h.c);h.area.value='요청 중 추가로 쓴 내용';h.area.events.input();vm.runInContext('release({ok:true,json:async()=>({})})',h.c);await saving;assert.equal(vm.runInContext('unsavedChanges',h.c),true);assert.equal(JSON.parse(h.storage.get('climateDraft:sample')).data.agreementReason,'요청 중 추가로 쓴 내용')});
test('automatic submit unlocks after failure and retries after backoff',async()=>{const h=harness();vm.runInContext('let attempts=0;fetch=async()=>{attempts++;throw Error("offline")}',h.c);await vm.runInContext('autoSubmitOnTime()',h.c);assert.equal(vm.runInContext('autoSubmitting',h.c),false);vm.runInContext('autoRetryAfter=0',h.c);await vm.runInContext('autoSubmitOnTime()',h.c);assert.equal(vm.runInContext('attempts',h.c),2)});
test('step four requires actor roles and reflection before final review',()=>{const h=harness();vm.runInContext("step=renderedStep=3;state={actors:[],actorAssignments:{}}",h.c);assert.match(vm.runInContext('validate()',h.c),/협력 주체/);vm.runInContext("session={country:'hanbit',data:{}};initState();state.opposingCountry='saebom'",h.c);const html=vm.runInContext('renderFastReflection()',h.c);assert.match(html,/reflectionReason/);assert.match(html,/국제협력을 실행할 주체/)});
