const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),{spawn}=require('child_process');
test('reserved time waits for teacher admission and student, survives restart, and enforces expiry',async()=>{
 const data=fs.mkdtempSync(path.join(os.tmpdir(),'climate-extra-')),port=5400+Math.floor(Math.random()*100),base=`http://127.0.0.1:${port}`,id='extra-test';
 fs.writeFileSync(path.join(data,'events.jsonl'),[{type:'start',sessionId:id,studentId:'30223',name:'황동식',className:'2반',country:'sun',ts:new Date().toISOString()},{type:'submit',sessionId:id,data:{priorityReason:'keep this'},elapsedSeconds:2700,timeComplianceScore:6,ts:new Date().toISOString()}].map(JSON.stringify).join('\n')+'\n');
 fs.writeFileSync(path.join(data,'runtime.json'),JSON.stringify({serverOpen:false,timerPaused:true}));
 let child;async function boot(){child=spawn(process.execPath,['server.js'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,PORT:String(port),DATA_DIR:data,TEACHER_PASSWORD:'test-only'},stdio:'ignore'});for(let n=0;n<100;n++){try{await fetch(base+'/health');return}catch{await new Promise(r=>setTimeout(r,30))}}throw Error('startup');}
 async function stop(){await new Promise(r=>{child.once('exit',r);child.kill()});}
 async function q(u,b,auth=true){const r=await fetch(base+u,{method:b?'POST':'GET',headers:{'Content-Type':'application/json',...(auth?{'x-teacher-key':'test-only'}:{})},body:b?JSON.stringify(b):undefined});return {http:r.status,...await r.json()};}
 try{await boot();assert.equal((await q('/api/teacher/individual-time',{sessionId:id,minutes:30},false)).http,401);assert.equal((await q('/api/teacher/individual-time',{sessionId:id,minutes:30})).http,200);
 let j=await q('/api/session/'+id);assert.equal(j.timer.remainingSeconds,1800);assert.equal(j.timer.paused,true);assert.equal(j.session.individualTime.startedAt,null);assert.equal(j.session.data.priorityReason,'keep this');await stop();await boot();
 j=await q('/api/teacher/submission-detail?sessionId='+id);assert.equal(j.session.individualTime.startedAt,null);await q('/api/teacher/server',{action:'open',classNo:2});j=await q('/api/teacher/submission-detail?sessionId='+id);assert.equal(j.session.individualTime.startedAt,null);
 j=await q('/api/start',{studentId:'30223',name:'황동식'},false);assert.equal(j.timer.phase,'running');assert.equal(j.timer.totalSeconds,1800);assert.ok(j.session.individualTime.startedAt);assert.equal((await q('/api/save',{sessionId:id,data:{agreementReason:'new'}},false)).http,200);
 await q('/api/teacher/server',{action:'close'});j=await q('/api/timer/'+id);assert.equal(j.paused,true);await stop();
 const events=fs.readFileSync(path.join(data,'events.jsonl'),'utf8').trim().split('\n').map(JSON.parse);events.find(e=>e.type==='individual_time_start').ts=new Date(Date.now()-1900000).toISOString();fs.writeFileSync(path.join(data,'events.jsonl'),events.map(JSON.stringify).join('\n')+'\n');await boot();await q('/api/teacher/server',{action:'open',classNo:2});j=await q('/api/timer/'+id);assert.equal(j.sessionStatus,'submitted');assert.equal(j.remainingSeconds,0);assert.equal((await q('/api/save',{sessionId:id,data:{priorityReason:'overwrite'}},false)).http,409);j=await q('/api/session/'+id);assert.equal(j.session.data.priorityReason,'keep this');assert.equal(j.session.data.agreementReason,'new');assert.equal(j.session.timeComplianceScore,6);
 }finally{if(child&&!child.killed)await stop();fs.rmSync(data,{recursive:true,force:true});}
});
