const http=require('http');const fs=require('fs');const path=require('path');const {URL}=require('url');
const ROOT=__dirname,FILE=path.join(ROOT,'index.html'),PORT=Number(process.env.PORT||3000),PIN=String(process.env.TEACHER_PIN||'123456'),DATABASE_URL=process.env.DATABASE_URL||'',DATA=path.join(ROOT,'data.json');let state=null,pg=null,q=Promise.resolve();
const blank=()=>({session:{is_open:0,closes_at:null},roster:{enabled:false,rows:[]},submissions:{},updated_at:new Date().toISOString()});const parse=(s,f=null)=>{try{return JSON.parse(s)}catch{return f}};const iso=()=>new Date().toISOString();const clone=x=>JSON.parse(JSON.stringify(x));
async function init(){if(DATABASE_URL){const {Pool}=require('pg');pg=new Pool({connectionString:DATABASE_URL,ssl:DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}});await pg.query('CREATE TABLE IF NOT EXISTS human_rights_kv (key TEXT PRIMARY KEY,value JSONB NOT NULL,updated_at TIMESTAMPTZ DEFAULT NOW())');let r=await pg.query('SELECT value FROM human_rights_kv WHERE key=$1',['state']);if(!r.rows.length)await pg.query('INSERT INTO human_rights_kv(key,value) VALUES($1,$2::jsonb)',['state',JSON.stringify(blank())])}else{state=fs.existsSync(DATA)?parse(fs.readFileSync(DATA,'utf8'),blank()):blank();await save(state)}}
async function get(){if(pg){let r=await pg.query('SELECT value FROM human_rights_kv WHERE key=$1',['state']);return r.rows[0]?.value||blank()}return clone(state||blank())}async function save(s){s.updated_at=iso();if(pg){await pg.query('INSERT INTO human_rights_kv(key,value,updated_at) VALUES($1,$2::jsonb,NOW()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()',['state',JSON.stringify(s)]);return}state=clone(s);q=q.then(()=>fs.promises.writeFile(DATA,JSON.stringify(state,null,2)));return q}
const sid=v=>String(v||'').trim().slice(0,30),name=v=>String(v||'').trim().slice(0,80);const pin=v=>String(v||'')===PIN;function open(x){return !!x?.is_open&&(!x.closes_at||Date.now()<new Date(x.closes_at).getTime())}function match(s,id,n){return !s.roster?.enabled||(s.roster.rows||[]).some(r=>String(r.student_id)===id&&String(r.name)===n)}
function send(res,st,b,h={}){res.writeHead(st,{'Cache-Control':'no-store',...h});res.end(b)}function json(res,st,o){send(res,st,JSON.stringify(o),{'Content-Type':'application/json; charset=utf-8'})}async function body(req){return new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>5e6){reject(Error('too large'));req.destroy()}});req.on('end',()=>resolve(parse(d,{})));req.on('error',reject)})}
async function api(req,res,u){
 if(u.pathname==='/api/bootstrap'&&req.method==='GET'){let s=await get();return json(res,200,{session:{...s.session,is_open:open(s.session)?1:0}})}
 if(u.pathname==='/api/login'&&req.method==='POST'){let b=await body(req),id=sid(b.student_id),n=name(b.name),s=await get();if(!id||!n)return json(res,400,{error:'학번과 이름을 입력하세요.'});if(!open(s.session))return json(res,403,{error:'현재 수행평가가 열려 있지 않습니다.'});if(!match(s,id,n))return json(res,403,{error:'등록된 학번과 이름이 일치하지 않습니다.'});let r=s.submissions[id];if(r&&r.name&&r.name!==n)return json(res,409,{error:'이 학번은 다른 이름으로 이미 기록되어 있습니다.'});if(!r){s.submissions[id]={student_id:id,name:n,payload:null,submitted:false,submitted_at:null,ai_grade:null,teacher_grade:null,teacher_comment:'',updated_at:iso()};await save(s)}return json(res,200,{ok:true})}
 if(u.pathname==='/api/progress'&&req.method==='GET'){let s=await get(),r=s.submissions[sid(u.searchParams.get('student_id'))];return json(res,200,r?{payload:r.payload||null,submitted:!!r.submitted,submitted_at:r.submitted_at||null}:{payload:null,submitted:false,submitted_at:null})}
 if(u.pathname==='/api/save'&&req.method==='POST'){let b=await body(req),id=sid(b.student_id),n=name(b.name),s=await get();if(!match(s,id,n))return json(res,403,{error:'명단과 일치하지 않습니다.'});let r=s.submissions[id]||{student_id:id,name:n,submitted:false,submitted_at:null,ai_grade:null,teacher_grade:null,teacher_comment:''};if(r.submitted)return json(res,409,{error:'이미 최종 제출된 답안입니다.'});r.name=n;r.payload=b.payload||{};r.updated_at=iso();s.submissions[id]=r;await save(s);return json(res,200,{ok:true,updated_at:r.updated_at})}
 if(u.pathname==='/api/submit'&&req.method==='POST'){let b=await body(req),id=sid(b.student_id),n=name(b.name),s=await get();if(!match(s,id,n))return json(res,403,{error:'명단과 일치하지 않습니다.'});let r=s.submissions[id]||{student_id:id,name:n,ai_grade:null,teacher_grade:null,teacher_comment:''};if(!r.submitted){r.name=n;r.payload=b.payload||{};r.submitted=true;r.submitted_at=iso();r.updated_at=r.submitted_at;s.submissions[id]=r;await save(s)}return json(res,200,{ok:true,submitted_at:r.submitted_at})}
 if(u.pathname==='/api/teacher/submissions'&&req.method==='GET'){if(!pin(u.searchParams.get('pin')))return json(res,401,{error:'교사 PIN이 올바르지 않습니다.'});let s=await get();return json(res,200,{rows:Object.values(s.submissions||{}).sort((a,b)=>String(a.student_id).localeCompare(String(b.student_id),'ko')),roster:{enabled:!!s.roster?.enabled,count:(s.roster?.rows||[]).length},ai_configured:false,session:s.session})}
 if(u.pathname==='/api/teacher/open'&&req.method==='POST'){let b=await body(req);if(!pin(b.pin))return json(res,401,{error:'교사 PIN이 올바르지 않습니다.'});let mins=Math.min(180,Math.max(5,Number(b.minutes)||45)),s=await get();s.session={is_open:1,closes_at:new Date(Date.now()+mins*60000).toISOString()};await save(s);return json(res,200,{ok:true,closes_at:s.session.closes_at})}
 if(u.pathname==='/api/teacher/close'&&req.method==='POST'){let b=await body(req);if(!pin(b.pin))return json(res,401,{error:'교사 PIN이 올바르지 않습니다.'});let s=await get();s.session={is_open:0,closes_at:iso()};await save(s);return json(res,200,{ok:true})}
 if(u.pathname==='/api/teacher/roster/import'&&req.method==='POST'){let b=await body(req);if(!pin(b.pin))return json(res,401,{error:'교사 PIN이 올바르지 않습니다.'});let rows=Array.isArray(b.rows)?b.rows:[],clean=[],seen=new Set();for(let x of rows){let id=sid(x.student_id),n=name(x.name);if(id&&n&&!seen.has(id)){clean.push({student_id:id,name:n});seen.add(id)}}let s=await get();s.roster.rows=clean;await save(s);return json(res,200,{ok:true,count:clean.length})}
 if(u.pathname==='/api/teacher/roster/toggle'&&req.method==='POST'){let b=await body(req);if(!pin(b.pin))return json(res,401,{error:'교사 PIN이 올바르지 않습니다.'});let s=await get();s.roster.enabled=!!b.enabled;await save(s);return json(res,200,{ok:true,enabled:s.roster.enabled})}
 if(u.pathname==='/api/teacher/grade'&&req.method==='POST'){let b=await body(req);if(!pin(b.pin))return json(res,401,{error:'교사 PIN이 올바르지 않습니다.'});let s=await get(),r=s.submissions[sid(b.student_id)];if(!r)return json(res,404,{error:'학생 기록을 찾지 못했습니다.'});r.teacher_grade=JSON.stringify(b.grade||{});r.teacher_comment=String(b.comment||'').slice(0,5000);r.updated_at=iso();await save(s);return json(res,200,{ok:true})}
 if(u.pathname==='/api/teacher/ai-grade'&&req.method==='POST')return json(res,501,{error:'현재 독립형 수행평가 서비스에서는 AI 가채점을 비활성화했습니다.'});return json(res,404,{error:'API를 찾을 수 없습니다.'})
}
init().then(()=>http.createServer(async(req,res)=>{try{let u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname.startsWith('/api/'))return api(req,res,u);if(u.pathname==='/health')return json(res,200,{ok:true,name:'인권도시 수행평가'});if(u.pathname==='/'||u.pathname==='/index.html'){let b=await fs.promises.readFile(FILE);return send(res,200,b,{'Content-Type':'text/html; charset=utf-8','Content-Disposition':'inline','X-Content-Type-Options':'nosniff'})}return send(res,404,'Not Found',{'Content-Type':'text/plain; charset=utf-8'})}catch(e){console.error(e);return json(res,500,{error:'서버 오류'})}}).listen(PORT,'0.0.0.0',()=>console.log(`인권도시 수행평가 : http://localhost:${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
