'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {URL}=require('url');
const ROOT=__dirname,PUBLIC_DIR=path.join(ROOT,'public'),SEED_DIR=path.join(ROOT,'seed');
const DATA_DIR=process.env.DATA_DIR||(fs.existsSync('/data')?'/data':path.join(ROOT,'data'));
const STUDENTS_DIR=path.join(DATA_DIR,'students'),PROGRESS_DIR=path.join(DATA_DIR,'progress'),GRADES_DIR=path.join(DATA_DIR,'grades'),PRESENCE_DIR=path.join(DATA_DIR,'presence'),TIME_DIR=path.join(DATA_DIR,'time');
const CONTROL_FILE=path.join(DATA_DIR,'control.json'),ROSTER_FILE=path.join(DATA_DIR,'roster.json'),AI_CONFIG_FILE=path.join(DATA_DIR,'ai_config.json'),MONITOR_TOKEN_FILE=path.join(DATA_DIR,'monitor_token.txt'),RESET_EPOCH_FILE=path.join(DATA_DIR,'reset_epoch.txt'),DEFAULT_ROSTER_FILE=path.join(SEED_DIR,'default_roster.json');
for(const d of [DATA_DIR,STUDENTS_DIR,PROGRESS_DIR,GRADES_DIR,PRESENCE_DIR,TIME_DIR])fs.mkdirSync(d,{recursive:true});
const PORT=Number(process.env.PORT||3000),TEACHER_PIN=String(process.env.TEACHER_PIN||'1234');
let openAIKey=String(process.env.OPENAI_API_KEY||'').trim(),openAIModel=String(process.env.OPENAI_GRADING_MODEL||'gpt-5.6-luna').trim();
const InitialCosts={central:24,welfare:18,hospital:39,market:20,park:18,school:8};
const FinalCosts={...InitialCosts,hospital:35};
const RESOURCE_IDS=new Set(['structure','usage','map','voices','budget']);
const EVIDENCE_IDS=new Set(['ev_hospital_mob','ev_central_all','ev_welfare_ratio','ev_welfare_center','ev_hospital_access','ev_market_elder','ev_school_route','ev_school_cost','ev_path','ev_wheel_voice','ev_hospital_voice','ev_budget50']);
const STATIONS=new Set(Object.keys(InitialCosts)),CRITERIA=new Set(['mobility','essential','many','efficiency','balance','urgent']),RIGHTS=new Set(['mobility_right','equality','life','dignity']),CITIZENS=new Set(['wheel','elder','hospital_user','student','worker','market_user','resident','parent']),LIMITS=new Set(['region','wait','cost','coverage','future']),REMEDIES=new Set(['next','support','budget','voice','plan']),IMPACTS=new Set(['budget','need','urgent','balance','none']),DECISIONS=new Set(['keep','partial','major']),STRENGTH=new Set(['small','medium','large']);
const RUBRIC_MAX={evidence_policy:25,rights_criteria:20,tradeoff:20,limit_remedy:15,revision:20};
function nowIso(){return new Date().toISOString()} function readJson(f){try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return null}} function writeJson(f,o){fs.mkdirSync(path.dirname(f),{recursive:true});const t=f+'.tmp-'+process.pid+'-'+crypto.randomBytes(4).toString('hex');fs.writeFileSync(t,JSON.stringify(o));fs.renameSync(t,f)}
function safeStudentId(id){const x=String(id||'').trim();if(!/^[A-Za-z0-9_-]{1,40}$/.test(x))throw Error('학번 형식이 올바르지 않습니다.');return x}
const studentFile=id=>path.join(STUDENTS_DIR,safeStudentId(id)+'.json'),progressFile=id=>path.join(PROGRESS_DIR,safeStudentId(id)+'.json'),gradeFile=id=>path.join(GRADES_DIR,safeStudentId(id)+'.json'),presenceFile=id=>path.join(PRESENCE_DIR,safeStudentId(id)+'.json'),timeFile=id=>path.join(TIME_DIR,safeStudentId(id)+'.json');
function listJson(d){try{return fs.readdirSync(d).filter(x=>x.endsWith('.json'))}catch{return[]}} function clearDirectoryJson(d){for(const f of listJson(d))try{fs.unlinkSync(path.join(d,f))}catch{}}
function resetGradesOnRevision(sid){const f=gradeFile(sid),g=readJson(f);if(!g)return;Object.assign(g,{ai_grade:null,ai_updated_at:null,teacher_grade:null,teacher_comment:'',teacher_updated_at:null,invalidated_at:nowIso()});writeJson(f,g)}
function getControl(){let c=readJson(CONTROL_FILE);if(!c||!Object.prototype.hasOwnProperty.call(c,'period_type')){c={is_open:0,class_no:0,period_type:'',session_id:'',opened_at:null,timer_running:false,remaining_seconds:0,closes_at:null};writeJson(CONTROL_FILE,c)}return c}
function getStudentClassNo(sid){if(sid==='000000')return 0;const m=String(sid).match(/^1(0[1-7])[0-9]{2}$/);if(m)return Number(m[1]);if(String(sid).startsWith('SIM')){const st=readJson(studentFile(sid));const cn=Number(st?.class_no||1);return cn>=1&&cn<=7?cn:1}return 0}
function getTimeRecord(sid,create=true){const f=timeFile(sid);let t=readJson(f);const z={student_id:sid,period1_used:0,period2_used:0,period1_attended:false,period2_attended:false,period1_segment_id:'',period2_segment_id:'',period1_active_seconds:0,period2_active_seconds:0,period1_last_heartbeat:null,period2_last_heartbeat:null,period1_confirmed:false,period2_confirmed:false,makeup_used:0,makeup_segment_id:'',makeup_active_seconds:0,makeup_last_heartbeat:null,makeup_confirmed:false,extra_used:0,penalty_exempt:false};if(!t){t={...z};if(create)writeJson(f,t)}else for(const[k,v]of Object.entries(z))if(!(k in t))t[k]=v;return t}
function saveTimeRecord(sid,t){writeJson(timeFile(sid),t)} function regularUsed(t){return Math.min(5400,Math.max(0,Number(t.period1_used||0)+Number(t.period2_used||0)+Number(t.makeup_used||0)))}
function liveHeartbeatDelta(last){if(!last)return 0;const d=Math.floor((Date.now()-new Date(last).getTime())/1000);return Math.min(15,Math.max(0,Number.isFinite(d)?d:0))}
function studentTimeIsLive(sid){const p=readJson(presenceFile(sid));return !!(p?.active&&!p.submitted&&p.last_seen&&Date.now()-new Date(p.last_seen).getTime()<=20000)}
function getTimePenalty(x){x=Number(x||0);if(x<=0)return 0;if(x<=600)return 2;if(x<=1200)return 4;return 6}
function studentSessionView(sid,create=true){const c=getControl(),t=getTimeRecord(sid,create),classNo=getStudentClassNo(sid),live=studentTimeIsLive(sid),base=regularUsed(t);let pendingRegular=0,pendingExtra=0,segmentRemaining=0,can=false,msg='현재 이 학생의 반 활동이 열려 있지 않습니다.';if(Number(c.is_open)===1&&(sid==='000000'||Number(c.class_no)===0||classNo===Number(c.class_no))){can=true;msg='';const pt=String(c.period_type);if(pt==='1'||pt==='2'){const pre=pt==='1'?'period1':'period2',used=Number(t[pre+'_used']||0),allow=Math.min(Math.max(0,2700-used),Math.max(0,5400-base));if(String(t[pre+'_segment_id'])===String(c.session_id)){const ld=live?liveHeartbeatDelta(t[pre+'_last_heartbeat']):0;pendingRegular=Math.min(Number(t[pre+'_active_seconds']||0)+ld,allow);segmentRemaining=Math.max(0,allow-pendingRegular)}else segmentRemaining=allow;if(allow<=0){can=false;msg=`${pt}차시 활동시간을 이미 모두 사용했습니다.`}}else if(pt==='makeup'){let active=0;if(String(t.makeup_segment_id)===String(c.session_id))active=Math.max(0,Number(t.makeup_active_seconds||0)+(live?liveHeartbeatDelta(t.makeup_last_heartbeat):0));const remain=Math.max(0,5400-base);pendingRegular=Math.min(active,remain);pendingExtra=Math.max(0,active-pendingRegular);segmentRemaining=Math.max(0,remain-pendingRegular)}}const remaining=Math.max(0,5400-base-pendingRegular),extra=Math.max(0,Number(t.extra_used||0)+pendingExtra),raw=getTimePenalty(extra),pen=t.penalty_exempt?0:raw;return{is_open:can?1:0,server_is_open:Number(c.is_open),class_no:Number(c.class_no),period_type:String(c.period_type),session_id:String(c.session_id),timer_running:can,remaining_seconds:remaining,segment_remaining_seconds:segmentRemaining,regular_used_seconds:Math.max(0,5400-remaining),extra_seconds:extra,total_used_seconds:Math.max(0,5400-remaining)+extra,time_penalty:pen,time_penalty_raw:raw,penalty_exempt:!!t.penalty_exempt,period1_used:Number(t.period1_used),period2_used:Number(t.period2_used),period1_attended:!!t.period1_attended,period2_attended:!!t.period2_attended,message:msg}}
function ensureTimeSegment(sid,meaningful,heartbeatActive){const c=getControl();if(Number(c.is_open)!==1)return;const cn=getStudentClassNo(sid);if(sid!=='000000'&&Number(c.class_no)!==0&&cn!==Number(c.class_no))return;const t=getTimeRecord(sid),now=nowIso();const update=pre=>{const seg=pre+'_segment_id',act=pre+'_active_seconds',hb=pre+'_last_heartbeat',conf=pre+'_confirmed';if(String(t[seg])!==String(c.session_id)){t[seg]=String(c.session_id);t[act]=0;t[hb]=now;t[conf]=false}if(heartbeatActive&&t[hb])t[act]=Number(t[act]||0)+liveHeartbeatDelta(t[hb]);t[hb]=now;if(meaningful||Number(t[act])>=180)t[conf]=true};if(String(c.period_type)==='1')update('period1');else if(String(c.period_type)==='2')update('period2');else if(String(c.period_type)==='makeup')update('makeup');saveTimeRecord(sid,t)}
function finalizeCurrentSession(){const c=getControl();if(Number(c.is_open)!==1)return;for(const name of listJson(TIME_DIR)){const t=readJson(path.join(TIME_DIR,name));if(!t)continue;const sid=String(t.student_id||name.replace(/\.json$/,''));if(sid!=='000000'&&Number(c.class_no)!==0&&getStudentClassNo(sid)!==Number(c.class_no))continue;const pt=String(c.period_type);if(pt==='1'||pt==='2'){const pre=pt==='1'?'period1':'period2';if(String(t[pre+'_segment_id'])===String(c.session_id)){if(t[pre+'_confirmed']){const add=Math.min(Math.max(0,Number(t[pre+'_active_seconds']||0)),Math.max(0,2700-Number(t[pre+'_used']||0)),Math.max(0,5400-regularUsed(t)));t[pre+'_used']=Number(t[pre+'_used']||0)+add;if(add>0)t[pre+'_attended']=true}t[pre+'_segment_id']='';t[pre+'_active_seconds']=0;t[pre+'_confirmed']=false;t[pre+'_last_heartbeat']=null}}else if(pt==='makeup'&&String(t.makeup_segment_id)===String(c.session_id)){if(t.makeup_confirmed){const active=Math.max(0,Number(t.makeup_active_seconds||0)),rem=Math.max(0,5400-regularUsed(t)),reg=Math.min(active,rem);t.makeup_used=Number(t.makeup_used||0)+reg;t.extra_used=Number(t.extra_used||0)+Math.max(0,active-reg)}Object.assign(t,{makeup_segment_id:'',makeup_active_seconds:0,makeup_confirmed:false,makeup_last_heartbeat:null})}saveTimeRecord(sid,t)}}
function getResetEpoch(){try{return Math.max(0,Number(fs.readFileSync(RESET_EPOCH_FILE,'utf8').trim())||0)}catch{return 0}} function bumpResetEpoch(){const v=Date.now();fs.writeFileSync(RESET_EPOCH_FILE,String(v));return v} function clearAllActivityData(){for(const d of[STUDENTS_DIR,PROGRESS_DIR,GRADES_DIR,PRESENCE_DIR,TIME_DIR])clearDirectoryJson(d);writeJson(CONTROL_FILE,{is_open:0,class_no:0,period_type:'',session_id:'',opened_at:null,timer_running:false,remaining_seconds:0,closes_at:nowIso()});return bumpResetEpoch()}
function resetStudentPeriod(sid,period){const t=getTimeRecord(sid);if(period==='1'){t.period1_used=0;t.period1_attended=false}else{t.period2_used=0;t.period2_attended=false}saveTimeRecord(sid,t);return studentSessionView(sid)} function setTimePenaltyExempt(sid,ex){const t=getTimeRecord(sid);t.penalty_exempt=!!ex;saveTimeRecord(sid,t);return studentSessionView(sid)}
function getRoster(){let r=readJson(ROSTER_FILE);if(!r){const seed=readJson(DEFAULT_ROSTER_FILE);r=seed?.rows?.length?{enabled:true,rows:seed.rows}:{enabled:false,rows:[]};writeJson(ROSTER_FILE,r)}if(!Array.isArray(r.rows))r.rows=[];return r}
function getAllStudentRefs(){const out=[],seen=new Set();for(const x of getRoster().rows){const sid=String(x.student_id||'').trim(),name=String(x.name||'').trim();if(sid&&name&&!seen.has(sid)){out.push({student_id:sid,name});seen.add(sid)}}for(const f of listJson(STUDENTS_DIR)){const st=readJson(path.join(STUDENTS_DIR,f)),sid=String(st?.student_id||'');if(sid&&!seen.has(sid)){out.push({student_id:sid,name:String(st.name||'')});seen.add(sid)}}return out}
function validateStudentIdentity(sid,name){if(sid==='000000')return{ok:true,name:'교사용테스트',test:true};if(!String(name||'').trim())return{ok:false,error:'학번과 이름을 입력해 주세요.'};const r=getRoster();if(r.enabled){const m=r.rows.find(x=>String(x.student_id)===sid);if(!m||String(m.name).trim()!==String(name).trim())return{ok:false,error:'명단에 없는 학번이거나 이름이 일치하지 않습니다. 학번과 이름을 다시 확인해 주세요.'}}return{ok:true,name:String(name).trim(),test:false}}
function saveStudent(sid,name){const f=studentFile(sid),old=readJson(f);if(old&&String(old.name).trim()!==String(name).trim())throw Error('이 학번은 다른 이름으로 이미 기록되어 있습니다. 학번을 확인하세요.');if(!old)writeJson(f,{student_id:sid,name,created_at:nowIso()})} function resetTestStudentData(){const sid='000000';for(const f of[progressFile(sid),gradeFile(sid),presenceFile(sid),timeFile(sid),studentFile(sid)])try{fs.unlinkSync(f)}catch{}}
function uniqueValid(arr,set){return Array.isArray(arr)&&arr.length===new Set(arr).size&&arr.every(x=>set.has(x))} function textIssue(text,min){const t=String(text||'').trim();if(t.length<min)return`최소 ${min}자 이상 작성하세요.`;if(/([.!?,~…;:])\1{4,}/u.test(t)||/(.)\1{6,}/u.test(t)||/(.{2,5})\1{3,}/u.test(t))return'같은 문자나 기호를 반복하지 말고 자신의 판단을 문장으로 작성하세요.';const letters=[...t].filter(ch=>/[가-힣A-Za-z0-9]/u.test(ch)).length;if(letters<Math.max(25,Math.floor(min*.45)))return'자신의 판단이 드러나도록 의미 있는 문장으로 작성하세요.';return''}
function planCost(ids,final=false){const m=final?FinalCosts:InitialCosts;return(ids||[]).reduce((s,id)=>s+(m[id]??999),0)}
function validatePayload(p,final=true){if(!p||typeof p!=='object')return'답안 데이터가 없습니다.';if(Number(p.schemaVersion)!==10)return'현재 수행평가 형식과 맞지 않는 이전 기록입니다. 새 활동을 시작해 주세요.';const seen=new Set(p.seen||[]),qdone=new Set(Object.keys(p.quizDone||{}).filter(k=>p.quizDone[k]));if(final&&(seen.size!==RESOURCE_IDS.size||[...RESOURCE_IDS].some(x=>!seen.has(x))||qdone.size!==RESOURCE_IDS.size||[...RESOURCE_IDS].some(x=>!qdone.has(x))))return'정책 자료 5개와 확인 문제를 모두 완료하세요.';if(!uniqueValid(p.evidence||[],EVIDENCE_IDS))return'핵심 근거 선택을 확인하세요.';if(final&&!((p.evidence||[]).length>=3&&(p.evidence||[]).length<=4))return'핵심 근거를 3~4개 선택하세요.';if(!uniqueValid(p.policyStations||[],STATIONS))return'1차 정책 설치역을 확인하세요.';if(final&&((p.policyStations||[]).length<2||planCost(p.policyStations)>50))return'1차 정책은 2곳 이상, 50억 원 이내여야 합니다.';if(!uniqueValid(p.criteria||[],CRITERIA))return'정책 기준을 확인하세요.';if(final&&(p.criteria||[]).length!==2)return'정책 기준을 2개 선택하세요.';if(!uniqueValid(p.rights||[],RIGHTS))return'관련 권리를 확인하세요.';if(final&&!((p.rights||[]).length>=1&&(p.rights||[]).length<=2))return'관련 권리를 1~2개 선택하세요.';if(final){let e=textIssue(p.answer1,100);if(e)return'정책 선택 이유: '+e}if(!uniqueValid(p.beneficiaries||[],CITIZENS)||!uniqueValid(p.delayed||[],CITIZENS))return'시민 집단 선택을 확인하세요.';if(final){const b=p.beneficiaries||[],d=p.delayed||[];if(b.length<1||b.length>2||d.length<1||d.length>2||b.some(x=>d.includes(x)))return'먼저 도움받는 시민과 상대적으로 기다리는 시민을 다시 확인하세요.'}if(p.limitation&&!LIMITS.has(p.limitation))return'정책의 한계를 확인하세요.';if(p.remedy&&!REMEDIES.has(p.remedy))return'보완 방법을 확인하세요.';if(final&&(!LIMITS.has(p.limitation)||!REMEDIES.has(p.remedy)))return'정책의 한계와 보완 방법을 선택하세요.';if(final){let e=textIssue(p.answer2,60);if(e)return'정책 영향과 보완: '+e}if(!uniqueValid(p.newImpacts||[],IMPACTS))return'새 정보의 영향을 확인하세요.';if((p.newImpacts||[]).includes('none')&&(p.newImpacts||[]).length>1)return'새 정보 영향 선택을 다시 확인하세요.';if(final&&(!(p.newImpacts||[]).length||!STRENGTH.has(p.impactStrength)))return'새 정보가 정책에 미치는 영향을 판단하세요.';if(p.finalDecision&&!DECISIONS.has(p.finalDecision))return'최종 판단 유형을 확인하세요.';if(!uniqueValid(p.finalStations||[],STATIONS))return'최종 정책 설치역을 확인하세요.';if(final){if(!DECISIONS.has(p.finalDecision))return'최종 판단을 선택하세요.';if((p.finalStations||[]).length<2||planCost(p.finalStations,true)>50)return'최종 정책은 2곳 이상, 50억 원 이내여야 합니다.';const same=[...(p.policyStations||[])].sort().join('|')===[...(p.finalStations||[])].sort().join('|');if(p.finalDecision==='keep'&&!same)return'정책 유지 선택과 최종 설치역이 일치하지 않습니다.';if(p.finalDecision!=='keep'&&same)return'정책 변경 선택과 최종 설치역을 다시 확인하세요.';let e=textIssue(p.answer3,100);if(e)return'최종 판단: '+e}return null}
function checkPin(v){return String(v||'')===TEACHER_PIN} function monitorToken(){try{const x=fs.readFileSync(MONITOR_TOKEN_FILE,'utf8').trim();if(x)return x}catch{}const x=crypto.randomBytes(24).toString('hex');fs.writeFileSync(MONITOR_TOKEN_FILE,x);return x} function checkMonitorToken(v){return!!v&&String(v)===monitorToken()}
function loadAiConfig(){if(openAIKey)return;const c=readJson(AI_CONFIG_FILE);if(c?.api_key)openAIKey=String(c.api_key).trim();if(c?.model)openAIModel=String(c.model).trim()} function saveAiConfig(key,model){openAIKey=String(key||'').trim();openAIModel=String(model||'gpt-5.6-luna').trim();if(!openAIKey)throw Error('API 키를 입력하세요.');writeJson(AI_CONFIG_FILE,{api_key:openAIKey,model:openAIModel,updated_at:nowIso()})} function clearAiConfig(){openAIKey=String(process.env.OPENAI_API_KEY||'').trim();openAIModel=String(process.env.OPENAI_GRADING_MODEL||'gpt-5.6-luna').trim();try{fs.unlinkSync(AI_CONFIG_FILE)}catch{}} function aiConfigured(){loadAiConfig();return!!openAIKey&&!!openAIModel}
async function openAIRequest(body){loadAiConfig();if(!openAIKey)throw Error('OpenAI API 키가 설정되지 않았습니다.');const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${openAIKey}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),txt=await r.text();let obj;try{obj=JSON.parse(txt)}catch{obj=null}if(!r.ok)throw Error(obj?.error?.message||txt||`OpenAI API 오류 ${r.status}`);return obj}
async function invokeAiPing(key,model){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:model||'gpt-5.6-luna',input:'Reply with OK.'})});if(!r.ok)throw Error('API 연결 확인에 실패했습니다.');return true}
async function invokeAiGrade(p){const labels={stations:{central:'새봄중앙역',welfare:'복지센터역',hospital:'대학병원역',market:'전통시장역',park:'푸른공원역',school:'새봄고역'},criteria:{mobility:'교통약자 보호',essential:'필수시설 접근',many:'많은 시민에게 혜택',efficiency:'예산 효율',balance:'지역 간 형평성',urgent:'문제의 긴급성'},rights:{mobility_right:'이동권',equality:'평등권',life:'인간다운 생활을 할 권리',dignity:'인간의 존엄과 가치'}};const student={evidence:p.evidence,policyStations:(p.policyStations||[]).map(x=>labels.stations[x]||x),criteria:(p.criteria||[]).map(x=>labels.criteria[x]||x),rights:(p.rights||[]).map(x=>labels.rights[x]||x),answer1:p.answer1,beneficiaries:p.beneficiaries,delayed:p.delayed,limitation:p.limitation,remedy:p.remedy,answer2:p.answer2,newImpacts:p.newImpacts,impactStrength:p.impactStrength,finalDecision:p.finalDecision,finalStations:(p.finalStations||[]).map(x=>labels.stations[x]||x),answer3:p.answer3};const prompt=`고등학교 1학년 통합사회 수행평가의 가채점 보조자입니다. 문장 표현의 세련됨보다 학생이 선택한 자료·권리·정책기준을 연결해 판단했는지 평가하세요. 역 선택 자체에는 정답 점수를 주지 마세요.\n평가: 자료와 정책 연결 25, 권리와 기준 연결 20, 수혜·대기 집단 비교 20, 한계와 보완 15, 새 정보 재판단 20.\n학생 기록:${JSON.stringify(student)}\n각 항목 점수와 2~4문장의 요약을 JSON으로만 답하세요.`;const schema={type:'object',additionalProperties:false,properties:{evidence_policy:{type:'integer',minimum:0,maximum:25},rights_criteria:{type:'integer',minimum:0,maximum:20},tradeoff:{type:'integer',minimum:0,maximum:20},limit_remedy:{type:'integer',minimum:0,maximum:15},revision:{type:'integer',minimum:0,maximum:20},summary:{type:'string'}},required:['evidence_policy','rights_criteria','tradeoff','limit_remedy','revision','summary']};const resp=await openAIRequest({model:openAIModel,input:prompt,text:{format:{type:'json_schema',name:'human_rights_v10_grade',strict:true,schema}},store:false});let out=resp.output_text;if(!out)for(const item of resp.output||[])for(const c of item.content||[])if(c.type==='output_text'&&c.text)out=c.text;if(!out)throw Error('AI 응답을 읽지 못했습니다.');const g=JSON.parse(out);g.total=['evidence_policy','rights_criteria','tradeoff','limit_remedy','revision'].reduce((s,k)=>s+Number(g[k]||0),0);return g}
function studentRow(st,teacher=false){const sid=String(st.student_id),p=readJson(progressFile(sid)),g=readJson(gradeFile(sid)),pr=readJson(presenceFile(sid)),tm=studentSessionView(sid,false);let online=!!(pr?.active&&pr.last_seen&&Date.now()-new Date(pr.last_seen).getTime()<=20000);const base={student_id:sid,name:st.name,payload:p?.payload||null,submitted:!!p?.submitted,submitted_at:p?.submitted_at||null,online,last_seen:pr?.last_seen||null,step:pr?.step||p?.payload?.step||0,active_seconds:Number(tm.total_used_seconds||0),time_penalty:Number(tm.time_penalty||0),time:tm};if(teacher)Object.assign(base,{ai_grade:g?.ai_grade||null,teacher_grade:g?.teacher_grade||null,teacher_comment:g?.teacher_comment||'',teacher_updated_at:g?.teacher_updated_at||null});return base}
function sendJson(res,obj,code=200){const b=Buffer.from(JSON.stringify(obj));res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Content-Length':b.length,'Cache-Control':'no-store'});res.end(b)} function sendError(res,msg,code=400,extra={}){sendJson(res,{error:msg,...extra},code)}
function serveStatic(res,pn){let rel=pn==='/'?'student.html':pn.replace(/^\/+/, '');const allowed=new Set(['student.html','manifest.json','sw.js','resource_01_structure.webp','resource_02_usage.webp','resource_03_map.webp','resource_04_voices.webp','resource_05_budget.webp']);if(!allowed.has(rel))return sendError(res,'없는 요청',404);const f=path.join(PUBLIC_DIR,rel);if(!fs.existsSync(f))return sendError(res,'파일 없음',404);const ext=path.extname(f),ct=ext==='.html'?'text/html; charset=utf-8':ext==='.json'?'application/manifest+json; charset=utf-8':ext==='.js'?'application/javascript; charset=utf-8':ext==='.webp'?'image/webp':'application/octet-stream',b=fs.readFileSync(f);res.writeHead(200,{'Content-Type':ct,'Content-Length':b.length,'Cache-Control':'no-store'});res.end(b)}
async function readBody(req){return await new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>5_000_000)req.destroy()});req.on('end',()=>{if(!s)return resolve({});try{resolve(JSON.parse(s))}catch{reject(Error('JSON 형식 오류'))}});req.on('error',reject)})}
async function handleGet(req,res,u){const q=Object.fromEntries(u.searchParams.entries());if(u.pathname==='/teacher'){res.writeHead(302,{Location:'/student.html?teacher=1'});return res.end()}if(u.pathname==='/student'){res.writeHead(302,{Location:'/student.html'});return res.end()}if(u.pathname==='/health')return sendJson(res,{ok:true,version:'v10.0',mode:'policy-board'});if(u.pathname==='/api/bootstrap'){const sid=String(q.student_id||'').trim();const session=sid?studentSessionView(safeStudentId(sid)):(()=>{const c=getControl();return{is_open:Number(c.is_open),server_is_open:Number(c.is_open),class_no:Number(c.class_no),period_type:String(c.period_type),session_id:String(c.session_id),timer_running:Number(c.is_open)===1,remaining_seconds:5400,extra_seconds:0,time_penalty:0,message:''}})();return sendJson(res,{version:'v10.0',session,reset_epoch:getResetEpoch()})}if(u.pathname==='/api/progress'){let sid;try{sid=safeStudentId(q.student_id)}catch(e){return sendError(res,e.message)}const p=readJson(progressFile(sid));return sendJson(res,{payload:p?.payload||null,submitted:!!p?.submitted,submitted_at:p?.submitted_at||null,time:studentSessionView(sid),reset_epoch:getResetEpoch()})}if(u.pathname==='/api/teacher/submissions'||u.pathname==='/api/teacher/dashboard'){if(!checkPin(q.pin))return sendError(res,'교사 PIN이 올바르지 않습니다.',403);const rows=getAllStudentRefs().sort((a,b)=>a.student_id.localeCompare(b.student_id)).filter(x=>x.student_id!=='000000').map(x=>studentRow(x,true)),r=getRoster(),c=getControl(),session={is_open:Number(c.is_open),class_no:Number(c.class_no),period_type:String(c.period_type),session_id:String(c.session_id)};if(u.pathname.endsWith('dashboard'))return sendJson(res,{students:rows,roster_enabled:!!r.enabled,roster_count:r.rows.length,ai_available:aiConfigured(),ai_model:openAIModel,session,monitor_token:monitorToken()});return sendJson(res,{rows,roster:{enabled:!!r.enabled,count:r.rows.length},ai_configured:aiConfigured(),ai_model:openAIModel,monitor_token:monitorToken(),session})}if(u.pathname==='/api/monitor/submissions'){if(!checkMonitorToken(q.token))return sendError(res,'교실 모니터 주소가 올바르지 않습니다.',403);const c=getControl(),rows=getAllStudentRefs().filter(x=>x.student_id!=='000000').map(x=>studentRow(x,false));return sendJson(res,{rows,session:{is_open:Number(c.is_open),class_no:Number(c.class_no),period_type:String(c.period_type)}})}return serveStatic(res,u.pathname)}
async function handlePost(req,res,u,b){if(u.pathname==='/api/login'){let sid;try{sid=safeStudentId(b.student_id)}catch(e){return sendError(res,e.message)}const chk=validateStudentIdentity(sid,b.name);if(!chk.ok)return sendError(res,chk.error,403,{code:'ROSTER_MISMATCH'});if(sid==='000000'&&!b.resume)resetTestStudentData();try{saveStudent(sid,chk.name)}catch(e){return sendError(res,e.message,409)}let sv=studentSessionView(sid);if(Number(sv.is_open)!==1){if(b.resume)return sendJson(res,{ok:1,name:chk.name,test:!!chk.test,session:sv});return sendError(res,sv.message,403,{code:'SESSION_NOT_OPEN'})}ensureTimeSegment(sid,false,false);return sendJson(res,{ok:1,name:chk.name,test:!!chk.test,session:studentSessionView(sid)})}
if(u.pathname==='/api/heartbeat'){let sid;try{sid=safeStudentId(b.student_id)}catch(e){return sendError(res,e.message)}const active=b.active==null?true:!!b.active;ensureTimeSegment(sid,false,active&&!b.submitted);writeJson(presenceFile(sid),{student_id:sid,last_seen:nowIso(),step:Math.max(0,Math.min(7,Number(b.step||0))),submitted:!!b.submitted,active,answer_lengths:[Number(b.answer1_length||0),Number(b.answer2_length||0),Number(b.answer3_length||0)]});return sendJson(res,{ok:1,session:studentSessionView(sid)})}
if(u.pathname==='/api/save'){let sid;try{sid=safeStudentId(b.student_id)}catch(e){return sendError(res,e.message)}const chk=validateStudentIdentity(sid,b.name);if(!chk.ok)return sendError(res,chk.error,403);const sv=studentSessionView(sid);if(Number(sv.is_open)!==1)return sendError(res,sv.message,403);const err=validatePayload(b.payload,false);if(err)return sendError(res,err,400);ensureTimeSegment(sid,true,true);const old=readJson(progressFile(sid));if(old?.submitted)resetGradesOnRevision(sid);try{saveStudent(sid,chk.name)}catch(e){return sendError(res,e.message,409)}writeJson(progressFile(sid),{student_id:sid,payload:b.payload,updated_at:nowIso(),submitted:false,submitted_at:null,first_submitted_at:old?.first_submitted_at||old?.submitted_at||null,last_submitted_at:old?.last_submitted_at||old?.submitted_at||null,submission_count:Number(old?.submission_count||(old?.submitted_at?1:0))});return sendJson(res,{ok:1,session:studentSessionView(sid)})}
if(u.pathname==='/api/submit'){let sid;try{sid=safeStudentId(b.student_id)}catch(e){return sendError(res,e.message)}const chk=validateStudentIdentity(sid,b.name);if(!chk.ok)return sendError(res,chk.error,403);const err=validatePayload(b.payload,true);if(err)return sendError(res,err,400);let sv=studentSessionView(sid);if(Number(sv.is_open)!==1)return sendError(res,sv.message,403);ensureTimeSegment(sid,true,true);sv=studentSessionView(sid);const old=readJson(progressFile(sid));if(old?.submitted)resetGradesOnRevision(sid);const ts=nowIso(),payload={...b.payload,submitted:true,receiptTime:ts};writeJson(progressFile(sid),{student_id:sid,payload,updated_at:ts,submitted:true,submitted_at:ts,first_submitted_at:old?.first_submitted_at||old?.submitted_at||ts,last_submitted_at:ts,submission_count:Number(old?.submission_count||0)+1,extra_seconds_at_submit:Number(sv.extra_seconds),time_penalty_at_submit:Number(sv.time_penalty),penalty_exempt_at_submit:!!sv.penalty_exempt});return sendJson(res,{ok:1,submitted_at:ts,extra_seconds:Number(sv.extra_seconds),time_penalty:Number(sv.time_penalty),penalty_exempt:!!sv.penalty_exempt})}
if(u.pathname.startsWith('/api/teacher/')&&!checkPin(b.pin))return sendError(res,'교사 PIN이 올바르지 않습니다.',403);
if(u.pathname==='/api/teacher/open'){let cls=Number(b.class_no||0);if(cls<0||cls>7)return sendError(res,'수업 반은 전체반 또는 1~7반 중에서 선택하세요.');const period=String(b.period_type||'').trim();if(!['1','2','makeup'].includes(period))return sendError(res,'1차시, 2차시 또는 보충·추가시간을 선택하세요.');const old=getControl();if(Number(old.is_open)===1)finalizeCurrentSession();writeJson(CONTROL_FILE,{is_open:1,class_no:cls,period_type:period,session_id:crypto.randomBytes(16).toString('hex'),opened_at:nowIso(),timer_running:true,remaining_seconds:0,closes_at:null});return sendJson(res,{ok:1,class_no:cls,period_type:period})}
if(u.pathname==='/api/teacher/close'){if(Number(getControl().is_open)===1)finalizeCurrentSession();writeJson(CONTROL_FILE,{is_open:0,class_no:0,period_type:'',session_id:'',opened_at:null,timer_running:false,remaining_seconds:0,closes_at:nowIso()});return sendJson(res,{ok:1})}
if(u.pathname==='/api/teacher/roster/import'||u.pathname==='/api/teacher/roster'){const rows=[];for(const x of b.rows||[])try{const sid=safeStudentId(x.student_id),name=String(x.name||'').trim();if(sid&&name)rows.push({student_id:sid,name})}catch{}const r=getRoster();writeJson(ROSTER_FILE,{enabled:!!r.enabled,rows});return sendJson(res,{ok:1,count:rows.length})}
if(u.pathname==='/api/teacher/roster/toggle'||u.pathname==='/api/teacher/roster_toggle'){const r=getRoster();writeJson(ROSTER_FILE,{enabled:!!b.enabled,rows:r.rows});return sendJson(res,{ok:1,enabled:!!b.enabled})}
if(u.pathname==='/api/teacher/reset-activity'||u.pathname==='/api/teacher/reset_all'){if(Number(getControl().is_open)===1)return sendError(res,'수업이 열려 있는 동안에는 초기화할 수 없습니다. 먼저 활동을 종료하세요.',409);if(u.pathname.endsWith('reset_all')&&b.confirm!=='초기화')return sendError(res,'확인 문구가 일치하지 않습니다.');return sendJson(res,{ok:1,reset_epoch:clearAllActivityData()})}
if(u.pathname==='/api/teacher/time-reset'){let sid;try{sid=safeStudentId(b.student_id)}catch(e){return sendError(res,e.message)}if(!['1','2'].includes(String(b.period)))return sendError(res,'차시 값 오류');return sendJson(res,{ok:1,time:resetStudentPeriod(sid,String(b.period))})}
if(u.pathname==='/api/teacher/time-exempt'){let sid;try{sid=safeStudentId(b.student_id)}catch(e){return sendError(res,e.message)}return sendJson(res,{ok:1,time:setTimePenaltyExempt(sid,!!b.exempt)})}
if(u.pathname==='/api/teacher/grade'){let sid;try{sid=safeStudentId(b.student_id)}catch(e){return sendError(res,e.message)}const grade=b.grade||{};for(const[k,max]of Object.entries(RUBRIC_MAX))if(Number(grade[k]||0)<0||Number(grade[k]||0)>max)return sendError(res,'채점 범위를 확인하세요.');const g=readJson(gradeFile(sid))||{};Object.assign(g,{student_id:sid,teacher_grade:grade,teacher_comment:String(b.comment||'').slice(0,3000),teacher_updated_at:nowIso()});writeJson(gradeFile(sid),g);return sendJson(res,{ok:1})}
if(u.pathname==='/api/teacher/ai-config'){if(Number(getControl().is_open)===1)return sendError(res,'학생 활동 중에는 API 연결 확인을 실행하지 않습니다.',409);const key=String(b.api_key||'').trim(),model=String(b.model||'gpt-5.6-luna').trim();try{await invokeAiPing(key,model);saveAiConfig(key,model);return sendJson(res,{ok:1,configured:true,model:openAIModel})}catch(e){return sendError(res,'API 연결 확인 실패: '+e.message,502)}}
if(u.pathname==='/api/teacher/ai-clear'){clearAiConfig();return sendJson(res,{ok:1,configured:aiConfigured(),model:openAIModel})}
if(u.pathname==='/api/teacher/ai-grade'||u.pathname==='/api/teacher/ai_grade'){if(Number(getControl().is_open)===1)return sendError(res,'학생 활동 중에는 AI 가채점을 실행하지 않습니다.',409);let sid;try{sid=safeStudentId(b.student_id)}catch(e){return sendError(res,e.message)}const p=readJson(progressFile(sid));if(!p?.submitted)return sendError(res,'최종 제출된 답안을 찾지 못했습니다.',404);try{const grade=await invokeAiGrade(p.payload),g=readJson(gradeFile(sid))||{};Object.assign(g,{student_id:sid,ai_grade:grade,ai_updated_at:nowIso()});writeJson(gradeFile(sid),g);return sendJson(res,{ok:1,grade})}catch(e){return sendError(res,e.message,502)}}
if(u.pathname==='/api/teacher/ai-grade-all'||u.pathname==='/api/teacher/ai_grade_all'){if(Number(getControl().is_open)===1)return sendError(res,'학생 활동 중에는 AI 가채점을 실행하지 않습니다.',409);if(!aiConfigured())return sendError(res,'OpenAI API 키가 설정되지 않았습니다.');let graded=0,failed=0;for(const st of getAllStudentRefs()){const sid=String(st.student_id);if(sid==='000000')continue;const p=readJson(progressFile(sid)),g=readJson(gradeFile(sid));if(!p?.submitted||g?.ai_grade)continue;try{const grade=await invokeAiGrade(p.payload),ng=g||{};Object.assign(ng,{student_id:sid,ai_grade:grade,ai_updated_at:nowIso()});writeJson(gradeFile(sid),ng);graded++}catch{failed++}}return sendJson(res,{ok:1,graded,failed})}
return sendError(res,'없는 요청',404)}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET')return await handleGet(req,res,u);if(req.method==='POST')return await handlePost(req,res,u,await readBody(req));return sendError(res,'지원하지 않는 요청',405)}catch(e){console.error(e);if(!res.headersSent)sendError(res,'서버 처리 오류: '+e.message,500);else res.end()}});
loadAiConfig();getControl();getRoster();monitorToken();server.listen(PORT,'0.0.0.0',()=>console.log(`HR CITY policy-board v10.0 listening on ${PORT}; data=${DATA_DIR}`));
